export const WORDS = [
    'APPLE',
    'BREAD',
    'CHAIR',
    'DANCE',
    'EARTH',
    'FROST',
    'GRASS',
    'HOUSE',
    'IGLOO',
    'JOKER',
    'KICKS',
    'LEMON',
    'MANGO',
    'NIGHT',
    'OCEAN',
    'PUNCH',
    'QUICK',
    'RIVER',
    'SMILE',
    'TABLE',
    'UMBRA',
    'VIRUS',
    'WORLD',
    'YOUTH',
    'ZEBRA',
    'ALERT',
    'BRAVE',
    'CLOCK',
    'DELTA',
    'ELBOW',
    'FABLE',
    'GRAND',
    'HELLO',
    'IVORY',
    'JUDGE',
    'KNEEL',
    'LIGHT',
    'MIGHT',
    'NOBLE',
    'OVALS',
    'PLUMB',
    'QUART',
    'RAVEN',
    'STARS',
    'TIGER',
    'UMBRE',
    'VITAL',
    'WIDOW',
    'XENON',
    'YIELD',
    'ZESTY',
    'APPLY',
    'BLITZ',
    'CRANE',
    'DROVE',
    'EMBER',
    'FILMS',
    'GLAZE',
    'HEART',
    'INFER',
    'JEWEL',
    'LUNCH',
    'MIXER',
    'NOVEL',
    'OASIS',
    'PRIZE',
    'QUOTA',
    'RADIO',
    'SIXTY',
    'TANGO',
    'UNZIP',
    'VALID',
    'WAGER',
    'XERIC',
    'YOGIC',
    'ZONAL',
    'ALIAS',
    'BRISK',
    'CHAMP',
    'DOZER',
    'FROWN',
    'GLOVE',
    'HINGE',
    'IMAGE',
    'KARMA',
    'LATCH',
    'MIRTH',
    'NIXON',
    'OUTER',
    'PLUMB',
    'QUARK',
    'RIDGE',
    'SUNNY',
    'TIGER',
    'USUAL',
    'REACT'
];

export enum Difficulty {
    EASY = 'EASY',
    NORMAL = 'NORMAL',
    HARD = 'HARD'
}

// 6 rows by default, we can change it to hold different rows, so as to change the game difficulty
export const DifficultyToRowNum: { [key: string]: number } = {
    [Difficulty.EASY]: 8,
    [Difficulty.NORMAL]: 6,
    [Difficulty.HARD]: 5
};
